### ISSUE TITLE
ds

### ISSUE THREAD

**Issue by shiv-jetwal90** [shiv-jetwal90/webpage#16]
daf

**Comment by shiv-jetwal90** [comment]
ready for review

**Comment by shiv-jetwal90** [comment]
ready for review

**Comment by shiv-jetwal90** [comment]
ready for review

**Comment by shiv-jetwal90** [comment]
Hi there. 
You can ask me to deploy / purge / update a deployment or to execute automation tests by replying:
- `/falkonrybot whatsup` to see what is running.
- `/falkonrybot deploy merlin:branch_name,riactor:branch_name` to deploy a branch in dev environment.
- `/falkonrybot deploy merlin:branch_name,riactor:branch_name on new environment` to deploy a branch in standalone new environment.
- `/falkonrybot update` to update a deployed branch in dev environment.
- `/falkonrybot purge` to purge a deployed branch in dev environment.
- `/falkonrybot purge new environment` to purge a standalone new environment.
- `/falkonrybot test teardown` to purge an environment started for hatch.
- `/falkonrybot test merlin-ui,merlin-api,riactor-api,tercel,edge,compatibility,adks using merlin:branch_name,riactor:branch_name,python-adk:branch_name,java-adk:branch_name,csharp-adk:branch_name,drill:branch_name,mongo:branch_name,kafka:branch_name,zookeeper:branch_name,hadoop:branch_name,datanode:branch_name,monitor:branch_name,redis:branch_name,logging-agent:branch_name,fluentd-kinesis:branch_name` to execute automation tests on the branch.
- `/falkonrybot test merlin-api using merlin:branch_name,riactor:branch_name keep-alive` to keep hatch alive after test completion. By default, I will teardown the hatch deployment.

**Comment by shiv-jetwal90** [comment]
Don't thank me. It's my job. BTW, I like chatting with humans but not at work :wink:

**Comment by shiv-jetwal90** [comment]
ready for review

**Comment by shiv-jetwal90** [comment]
ready for review

**Comment by phagunbaya** [comment]
It has been more than 2 days that the lgtm has been requested for this issue. Please update

**Comment by phagunbaya** [comment]
It has been more than 2 days that the lgtm has been requested for this issue. Please update
